
	[sniper]
timing_system_preference = "ckm"
cycle_timing_systems = true # Go through each timing system until droptime is successfully grabbed
auto_claim_namemc = false

snipe_requests = 2 # requests to be sent per acc for normal sniping
prename_requests = 6 # requests to be sent per acc for prename sniping

[accounts]
max_accounts = 1
prename_max_accounts = 10

start_auth = 720 # start auth 720 minutes before drop

[skin]
change_skin_on_snipe = false
skin_change_type = "url"
skin = "" # this value depends onn the skin_change_type value

[announce]
mcsnipergo_announce_code = "" # leave blank to not announce snipe


# discord webhook-related things
webhook_url = "" # public webhook url to announce snipe
webhook_format = "sniped {name} with {searches} searches using MCsniperGO!"

private_webhook_url = "" # webhook url where PRIVATE information will be sent, DO NOT MAKE THIS IN A PUBLIC DISCORD CHANNEL.
private_webhook_format = "sniped {name} with {searches} searches and {offset} offset!"
private_webhook_include_acc = false # include acc details in webhook